version: '3.1'

services:

  mongo:
    image: mongo:4.0.10-xenial
    container_name: mongo-4.0.10
    volumes:
      - /opt/mongodb-data:/data/db
    ports:
      - 8142:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: roots3creT

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8140:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: roots3creT